
platform :ios, '13.0'

target 'DtpStat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'YandexMapKit'
  pod 'Alamofire', '~> 5.2'

end
